/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>

#include "interface.h"
#include "support.h"

int
main (int argc, char *argv[])
{
  GtkWidget *Authentification;
  GtkWidget *Gestion_liste___lectoral;
  GtkWidget *Gestion_observateurs;
  GtkWidget *Gestion_utilisateurs;
  GtkWidget *Gestion_du_BV;

#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif

  gtk_set_locale ();
  gtk_init (&argc, &argv);

  add_pixmap_directory (PACKAGE_DATA_DIR "/" PACKAGE "/pixmaps");

  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */
  Authentification = create_Authentification ();
  gtk_widget_show (Authentification);
  Gestion_liste___lectoral = create_Gestion_liste___lectoral ();
  gtk_widget_show (Gestion_liste___lectoral);
  Gestion_observateurs = create_Gestion_observateurs ();
  gtk_widget_show (Gestion_observateurs);
  Gestion_utilisateurs = create_Gestion_utilisateurs ();
  gtk_widget_show (Gestion_utilisateurs);
  Gestion_du_BV = create_Gestion_du_BV ();
  gtk_widget_show (Gestion_du_BV);

  gtk_main ();
  return 0;
}

