/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_Authentification (void);
GtkWidget* create_Gestion_liste___lectoral (void);
GtkWidget* create_Gestion_observateurs (void);
GtkWidget* create_Gestion_utilisateurs (void);
GtkWidget* create_Gestion_du_BV (void);
GtkWidget* create_vote (void);
